-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- INOVA.dbo.PERFIL definition

-- Drop table

-- DROP TABLE INOVA.dbo.PERFIL;

CREATE TABLE INOVA.dbo.PERFIL (
	ID_PERFIL tinyint NOT NULL,
	NOME_PERFIL varchar(50) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT PERFIL_PK PRIMARY KEY (ID_PERFIL)
);


-- INOVA.dbo.RISCO definition

-- Drop table

-- DROP TABLE INOVA.dbo.RISCO;

CREATE TABLE INOVA.dbo.RISCO (
	ID_RISCO tinyint NOT NULL,
	NOME_RISCO varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	CONSTRAINT RISCO_PK PRIMARY KEY (ID_RISCO)
);


-- INOVA.dbo.FUNDO definition

-- Drop table

-- DROP TABLE INOVA.dbo.FUNDO;

CREATE TABLE INOVA.dbo.FUNDO (
	CD_FNDO int NOT NULL,
	NOME_FNDO varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	CNPJ_FNDO bigint NOT NULL,
	DT_ABERTURA_FNDO date NOT NULL,
	DT_ENCERRAMENTO_FNDO date NULL,
	ID_RISCO tinyint NOT NULL,
	CONSTRAINT FUNDO_PK PRIMARY KEY (CD_FNDO),
	CONSTRAINT FUNDO_UN UNIQUE (CNPJ_FNDO),
	CONSTRAINT FUNDO_FK FOREIGN KEY (ID_RISCO) REFERENCES INOVA.dbo.RISCO(ID_RISCO)
);
 CREATE NONCLUSTERED INDEX FUNDO_ID_RISCO_IDX ON dbo.FUNDO (  ID_RISCO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- INOVA.dbo.COTA definition

-- Drop table

-- DROP TABLE INOVA.dbo.COTA;

CREATE TABLE INOVA.dbo.COTA (
	DT_COTA date NOT NULL,
	CD_FNDO int NOT NULL,
	COT_FNDO float NOT NULL,
	CONSTRAINT COTA_PK PRIMARY KEY (DT_COTA,CD_FNDO),
	CONSTRAINT COTA_FK FOREIGN KEY (CD_FNDO) REFERENCES INOVA.dbo.FUNDO(CD_FNDO)
);
 CREATE NONCLUSTERED INDEX COTA_COD_FUNDO_IDX ON dbo.COTA (  CD_FNDO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
